### PR TITLE
Fix mixin so no more attacks

### PR DESCRIPTION
**Pull request by MaayanSG**

### CODE REVIEW

**Comment by LeoCornelius** [comment]
You can't just delete those varables..

**Comment by MaayanSG** [comment]
what?

**Comment by MaayanSG** [comment]
that's how TRTG does it, it works

**Comment by LeoCornelius** [comment]
Yeah but the base code of keg needs those variables I have fixed it my self but thanks

**Comment by MaayanSG** [comment]
oh u have it done differently oof
np

**Pull request closed without merging**
