### PR TITLE
Update CryptoNoteConfig.h

### PR DESCRIPTION
**Pull request by JulianGameZ**

### CODE REVIEW

**Comment by JulianGameZ** [comment]
💩

**Comment by JulianGameZ** [comment]
💩

**Comment by JulianGameZ** [comment]
💩

**Comment by JulianGameZ** [comment]
🖕🏻

**Comment by UnrealValentin** [comment]
I think you didn't know that the Cryptowar is over.
PS: If you didn't know the Cake... it's a lie.

**Pull request closed without merging**
